# To use:
#
#   $ conda env create -f environment.yml  # `mamba` works too for this command
#   $ conda activate spk2py-dev
#
name: spk2py
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy<=1.23.5 # to avoid conflicts with numba
  - pandas
  - matplotlib
  - h5py
  - pillow
  - Opencv
  - scipy
  - scikit-learn
  - scikit-image
  - openpyxl
  - OpenSSL
  - datashader
  - imageio
  - compilers
  - openblas
  - setuptools=59.2.0
  - pkg-config
  - meson-python
  - pip
  - spin
  # For type annotations
  - typing_extensions>=4.2.0  # needed for python < 3.10
  - mypy=1.5.1
  # For building docs
  - sphinx>=4.5.0
  - sphinx-design
  - numpydoc=1.4.0
  - ipython
  - scipy
  - pandas
  - matplotlib
  - pydata-sphinx-theme=0.13.3
  # NOTE: breathe 4.33.0 collides with sphinx.ext.graphviz
  - breathe>4.33.0
  # For linting
  - pycodestyle=2.7.0
  - gitpython
  # Used in some tests
  - cffi
  - pytz
