# To use:
#   $ conda env create -f environment.yml  # `camba`, or use mamba:
#   $ mamba env create -f environment.yml  # `conda` works too for this command
#   $ conda activate clustersort # conda or mamba doesn't matter here

name: clustersort
channels:
  - conda-forge
  - default
dependencies:
  - black
  - packaging
  - mypy
  - pip
  - pydata-sphinx-theme
  - sphinx_rtd_theme
  - numpydoc
  - sphinx
  - setuptools
  - toml
  - wheel
  - datashader
  - matplotlib
  - vispy
  - datashader
  - pyqt
  - pyqt5-sip
  - pyqt-stubs
  - openpyxl
  - h5py
  - py-opencv
  - opencv
  - openssl
  - pillow
  - pyyaml
  - pyopenssl
  - numpy<=1.23.5
  - numba
  - pandas
  - scikit-learn
  - scikit-image
  - scipy
  - seaborn
  - tifffile
  - statsmodels
  - umap-learn
  - pip:
    - sonpy