version: 2.1

orbs:
  python: circleci/python@2.1.1

_defaults: &defaults
  docker:
    - image: cimg/python:3.9
  working_directory: ~/repo

jobs:
  docs-build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dev dependencies
          command: pip install sphinx numpydoc matplotlib pydata_sphinx_theme sphinx_design
      - run:
          name: Build docs
          command: |
            cd doc
            make clean
            make html

      - persist_to_workspace:
          root: doc/build
          paths: html

  docs-deploy:
    docker:
        - image: cimg/node:16.20
    steps:
      - checkout
      - attach_workspace:
          at: doc/build
      - run:
          name: Install and configure dependencies
          command: |
            sudo npm install -g gh-pages 
            git config --global user.email "FlynnOConnell@gmail.com"
            git config --global user.name "Flynn OConnell"
      - run:
          name: Disable jekyll
          command: touch doc/build/html/.nojekyll
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            ls -la
            gh-pages --message "[skip ci] Updates" -d doc/build/html

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - docs-build
      - docs-deploy:
          requires:
            - docs-build
          filters:
            branches:
              only: master
