version: 2.1

orbs:
  python: circleci/python@2.1.1

_defaults: &defaults
  docker:
    - image: cimg/python:3.9
  working_directory: ~/repo

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install sphinx numpydoc matplotlib pydata_sphinx_theme sphinx_design sphinx_rtd_theme IPython
      - run:
          name: Build docs
          command: |
            sphinx-build -b html doc/source doc/build/
      - persist_to_workspace:
        root: .
        paths:
          - doc/build

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email "FlynnOConnell@gmail.com"
            git config --global user.name "Flynn OConnell"
            git clone --branch gh-pages https://github.com/flynnoconnell/spk2py.git gh-pages
            cp -a ~/repo/doc/build/* gh-pages
            cd gh-pages
            touch .nojekyll
            git add -A
            git commit -m "Update documentation"
            git push origin gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
