version: 2.1

jobs:
  docs-build:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Setup Mamba
          command: |
            pwd
            wget -O Mambaforge.sh  "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
            bash Mambaforge.sh -b -p "${HOME}/conda"
            echo ". ${HOME}/conda/etc/profile.d/conda.sh" >> $BASH_ENV
            source "${HOME}/conda/etc/profile.d/conda.sh"
            source "${HOME}/conda/etc/profile.d/mamba.sh"
      - run:
          name: Install deps
          command: |
            conda env create -f environment.yml
            echo "export PATH=${HOME}/conda/envs/spk2py/bin:$PATH" >> $BASH_ENV
            conda activate spk2py
            pip install -r requirements.txt
      - run:
          name: Build docs
          command: cd docs/ && make html
      - persist_to_workspace:
          root: docs/_build
          paths: html

  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/_build
      - run:
          name: Disable jekyll
          command: touch docs/_build/html/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "FlynnOConnell@gmail.com"
            git config user.name "Flynn OConnell"

      - add_ssh_keys:
          fingerprints:
            - "72:78:77:81:46:2f:b5:6c:a0:b0:91:a9:9a:c6:3a:24"

      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/_build/html

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - docs-build
      - docs-deploy:
          requires:
            - docs-build
          filters:
            branches:
              only: master
