version: 2.1

orbs:
  python: circleci/python@2.1.1

_defaults: &defaults
  docker:
    - image: cimg/python:3.9
  working_directory: ~/repo

jobs:
  docs-build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Setup Mamba
          command: |
            pwd
            echo 'export PYTHONPATH=$PYTHONPATH:$(pwd)' >> $BASH_ENV
            curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
            bash Mambaforge-$(uname)-$(uname -m).sh -b # auto accept
            source ~/miniforge3/bin/activate
            conda config --set always_yes yes --set changeps1 no
      - run:
          name: Install deps
          command: |
            mamba install -f environment.yml
            pip install -r requirements.txt
      - run:
          name: Build docs
          command: |
            cd doc
            # with makefile
            make clean
            make html

      - persist_to_workspace:
          root: ~/repo
          paths:
            - doc/build/html

  docs-deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install system deps
          command: sudo apt-get update && sudo apt-get install -y rsync
      - run:
          name: Configure git
          command: |
            git config --global user.email "FlynnOConnell@gmail.com"
            git config --global user.name "Flynn OConnell"
      - run:
          name: Disable jekyll
          command: touch doc/build/html/.nojekyll
      - add_ssh_keys:
          fingerprints:
            - "72:78:77:81:46:2f:b5:6c:a0:b0:91:a9:9a:c6:3a:24"
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            ls -la
            git fetch origin gh-pages:gh-pages 
            git checkout gh-pages 
            rsync -av ~/repo/doc/build/html/ . 
            git add . 
            git diff --cached --quiet || git commit -m "[skip ci] Updates" && git push origin gh-pages
            git push origin gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - docs-build
      - docs-deploy:
          requires:
            - docs-build
          filters:
            branches:
              only: master
